name: KatalonDockerCI
on:
  push:
    branches:
      - github_action
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
        KS_VERSION: 7.2.1
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name : Prepare docker install 
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
    - name: Docker Login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} > ./my_password.txt
        cat ./my_password.txt
        cat ./my_password.txt | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Prepare 
      run: |
        chmod u+x ./build/*.sh
        ./build/prevent_overwrite_existing_tag.sh $KS_VERSION
    - name:  Build
      run: |
          chmod u+x ./build/*.sh
          ./build/clean.sh $KS_VERSION
          ./build/build.sh $KS_VERSION
          ./build/tag.sh $KS_VERSION
          chmod u+x ./test/project/*.sh
          cd ./test/project && ./run_chrome.sh $KS_VERSION ${{ secrets.API_KEY }}
          cd ./test/project && ./run_chrome_root.sh $KS_VERSION ${{ secrets.API_KEY }}
          cd ./test/project && ./run_chrome_advanced.sh $KS_VERSION ${{ secrets.API_KEY }}
          cd ./test/project && ./run_firefox.sh $KS_VERSION ${{ secrets.API_KEY }}
    - name: Push to dockerhub
      run: |
             ./build/tag.sh $KS_VERSION
             ./build/push.sh $KS_VERSION
             ./build/tag.sh latest
             ./build/push.sh latest