name: KatalonDockerCI
on:
  push:
    branches:
      - aws_ecr
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
        KS_VERSION: 7.4.2
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name : Prepare docker install 
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo apt -y install jq
    - name: Prepare 
      run: |
        chmod u+x ./build/*.sh
        ./build/prevent_overwrite_existing_tag.sh $KS_VERSION
    - name:  Build
      run: |
        chmod u+x ./build/*.sh
        ./build/clean.sh $KS_VERSION
        ./build/build.sh $KS_VERSION
        ./build/tag.sh $KS_VERSION 
    - name: Test
      run: | 
        chmod u+x ./test/project/*.sh
        cd $GITHUB_WORKSPACE/test/project && rm -rfv ./bin && ./run_chrome.sh $KS_VERSION ${{ secrets.API_KEY }}
        cd $GITHUB_WORKSPACE/test/project && rm -rfv ./bin && ./run_chrome_root.sh $KS_VERSION ${{ secrets.API_KEY }}
        cd $GITHUB_WORKSPACE/test/project && rm -rfv ./bin && ./run_chrome_advanced.sh $KS_VERSION ${{ secrets.API_KEY }}
        cd $GITHUB_WORKSPACE/test/project && rm -rfv ./bin && ./run_firefox.sh $KS_VERSION ${{ secrets.API_KEY }}
      continue-on-error: true
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        IMAGE_TAG: $KS_VERSION
      run: |
        ./build/tag.sh $KS_VERSION
        ./build/push.sh $KS_VERSION
        ./build/tag.sh latest
        ./build/push.sh latest
    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
