name: KatalonDockerCI
on:
  push:
    branches:
      - fix_bug
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
        KS_VERSION: 7.2.2
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name : Prepare docker install 
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo apt -y install jq
    - name: Log in to Docker
      uses: azure/docker-login@v1
      with:
          login-server: 'registry.hub.docker.com'
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
    - name: Prepare 
      run: |
        chmod u+x ./build/*.sh
        ./build/prevent_overwrite_existing_tag.sh $KS_VERSION
    - name:  Build
      run: |
          chmod u+x ./build/*.sh
          ./build/clean.sh $KS_VERSION
          ./build/build.sh $KS_VERSION
          ./build/tag.sh $KS_VERSION
          chmod u+x ./test/project/*.sh
          cd ./test/project && ./run_chrome.sh $KS_VERSION ${{ secrets.API_KEY }}
          cd ./test/project && ./run_chrome_root.sh $KS_VERSION ${{ secrets.API_KEY }}
          cd ./test/project && ./run_chrome_advanced.sh $KS_VERSION ${{ secrets.API_KEY }}
          cd ./test/project && ./run_firefox.sh $KS_VERSION ${{ secrets.API_KEY }}
    - name: Push to dockerhub
      run: |
             ./build/tag.sh $KS_VERSION
             ./build/push.sh $KS_VERSION
             ./build/tag.sh latest
             ./build/push.sh latest
